-- DAILY BUDGET MASTER - SAFE CHUNK UPLOAD WITH PROGRESS SUPPORT
CREATE TABLE IF NOT EXISTS public.daily_budget_stage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id uuid NOT NULL,
  customer_code text NOT NULL,
  party_name text, sm text, order_type text, area text, division text, planned_day text,
  yearly_budget numeric DEFAULT 0,
  apr_budget numeric DEFAULT 0, may_budget numeric DEFAULT 0, jun_budget numeric DEFAULT 0,
  jul_budget numeric DEFAULT 0, aug_budget numeric DEFAULT 0, sep_budget numeric DEFAULT 0,
  oct_budget numeric DEFAULT 0, nov_budget numeric DEFAULT 0, dec_budget numeric DEFAULT 0,
  jan_budget numeric DEFAULT 0, feb_budget numeric DEFAULT 0, mar_budget numeric DEFAULT 0,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_daily_budget_stage_batch ON public.daily_budget_stage(batch_id);
ALTER TABLE public.daily_budget_stage ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.raj_daily_budget_start_upload(p_session_token text,p_device_id text)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path='public' AS $$
DECLARE v uuid:=gen_random_uuid(); BEGIN
  PERFORM public.raj_outstanding_assert_session(p_session_token,p_device_id); RETURN v;
END $$;

CREATE OR REPLACE FUNCTION public.raj_daily_budget_add_chunk(p_session_token text,p_device_id text,p_batch_id uuid,p_rows jsonb)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path='public' AS $$
DECLARE v_count integer:=0; BEGIN
  PERFORM public.raj_outstanding_assert_session(p_session_token,p_device_id);
  IF p_batch_id IS NULL THEN RAISE EXCEPTION 'Upload Batch ID is required'; END IF;
  IF p_rows IS NULL OR jsonb_typeof(p_rows)<>'array' THEN RAISE EXCEPTION 'Budget rows must be a JSON array'; END IF;
  INSERT INTO public.daily_budget_stage(batch_id,customer_code,party_name,sm,order_type,area,division,planned_day,yearly_budget,apr_budget,may_budget,jun_budget,jul_budget,aug_budget,sep_budget,oct_budget,nov_budget,dec_budget,jan_budget,feb_budget,mar_budget)
  SELECT p_batch_id, regexp_replace(trim(coalesce(x.customer_code,'')),'\.0$',''), nullif(trim(x.party_name),''),nullif(trim(x.sm),''),nullif(trim(x.order_type),''),nullif(trim(x.area),''),nullif(trim(x.division),''),nullif(trim(x.planned_day),''),
    coalesce(x.yearly_budget,0),coalesce(x.apr_budget,0),coalesce(x.may_budget,0),coalesce(x.jun_budget,0),coalesce(x.jul_budget,0),coalesce(x.aug_budget,0),coalesce(x.sep_budget,0),coalesce(x.oct_budget,0),coalesce(x.nov_budget,0),coalesce(x.dec_budget,0),coalesce(x.jan_budget,0),coalesce(x.feb_budget,0),coalesce(x.mar_budget,0)
  FROM jsonb_to_recordset(p_rows) AS x(customer_code text,party_name text,sm text,order_type text,area text,division text,planned_day text,yearly_budget numeric,apr_budget numeric,may_budget numeric,jun_budget numeric,jul_budget numeric,aug_budget numeric,sep_budget numeric,oct_budget numeric,nov_budget numeric,dec_budget numeric,jan_budget numeric,feb_budget numeric,mar_budget numeric)
  WHERE nullif(regexp_replace(trim(coalesce(x.customer_code,'')),'\.0$',''),'') IS NOT NULL;
  GET DIAGNOSTICS v_count=ROW_COUNT; RETURN v_count;
END $$;

CREATE OR REPLACE FUNCTION public.raj_daily_budget_finish_upload(p_session_token text,p_device_id text,p_batch_id uuid,p_file_name text,p_uploaded_by text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='public' AS $$
DECLARE v_upload_id uuid; v_total integer; BEGIN
  PERFORM public.raj_outstanding_assert_session(p_session_token,p_device_id);
  SELECT count(*) INTO v_total FROM public.daily_budget_stage WHERE batch_id=p_batch_id;
  IF coalesce(v_total,0)=0 THEN RAISE EXCEPTION 'No Budget rows found in upload batch'; END IF;
  INSERT INTO public.daily_budget_uploads(file_name,uploaded_by,total_customers) VALUES(p_file_name,p_uploaded_by,v_total) RETURNING id INTO v_upload_id;
  -- WHERE clause intentionally present for Supabase safe-update rules.
  UPDATE public.daily_customer_budget SET is_active=false,updated_at=now() WHERE customer_code IS NOT NULL;
  INSERT INTO public.daily_customer_budget(customer_code,party_name,sm,order_type,area,division,planned_day,yearly_budget,apr_budget,may_budget,jun_budget,jul_budget,aug_budget,sep_budget,oct_budget,nov_budget,dec_budget,jan_budget,feb_budget,mar_budget,is_active,last_upload_id,updated_at)
  SELECT customer_code,party_name,sm,order_type,area,division,planned_day,yearly_budget,apr_budget,may_budget,jun_budget,jul_budget,aug_budget,sep_budget,oct_budget,nov_budget,dec_budget,jan_budget,feb_budget,mar_budget,true,v_upload_id,now()
  FROM public.daily_budget_stage WHERE batch_id=p_batch_id
  ON CONFLICT(customer_code) DO UPDATE SET party_name=excluded.party_name,sm=excluded.sm,order_type=excluded.order_type,area=excluded.area,division=excluded.division,planned_day=coalesce(excluded.planned_day,daily_customer_budget.planned_day),yearly_budget=excluded.yearly_budget,apr_budget=excluded.apr_budget,may_budget=excluded.may_budget,jun_budget=excluded.jun_budget,jul_budget=excluded.jul_budget,aug_budget=excluded.aug_budget,sep_budget=excluded.sep_budget,oct_budget=excluded.oct_budget,nov_budget=excluded.nov_budget,dec_budget=excluded.dec_budget,jan_budget=excluded.jan_budget,feb_budget=excluded.feb_budget,mar_budget=excluded.mar_budget,is_active=true,last_upload_id=v_upload_id,updated_at=now();
  DELETE FROM public.daily_budget_stage WHERE batch_id=p_batch_id;
  RETURN jsonb_build_object('success',true,'upload_id',v_upload_id,'total_customers',v_total);
END $$;

CREATE OR REPLACE FUNCTION public.raj_daily_budget_cancel_upload(p_session_token text,p_device_id text,p_batch_id uuid)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path='public' AS $$ BEGIN
  PERFORM public.raj_outstanding_assert_session(p_session_token,p_device_id);
  DELETE FROM public.daily_budget_stage WHERE batch_id=p_batch_id; RETURN true;
END $$;

GRANT EXECUTE ON FUNCTION public.raj_daily_budget_start_upload(text,text) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.raj_daily_budget_add_chunk(text,text,uuid,jsonb) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.raj_daily_budget_finish_upload(text,text,uuid,text,text) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.raj_daily_budget_cancel_upload(text,text,uuid) TO anon,authenticated;
